openapi: 3.0.1
info:
  title: '@jupiterone/graph-sonarcloud'
  description: A JupiterOne Integration for ingesting data of the SonarCloud
  x-cortex-git:
    github:
      repository: JupiterOne/graph-sonarcloud
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-sonarcloud'
  x-cortex-service-groups:
    - tier-4
